### ISSUE TITLE
Persistent Slots

### ISSUE THREAD

**Issue by derbismarck** [SignalCommunity/SCMF#1]
Switching BWMF code to work on persistent slots using respawntype base.

**Comment by JonBons** [comment]
Initial work for this done in commit #c8b7d944b684c6483bab8898ab10a37f888eecde

**Comment by derbismarck** [comment]
We also need to do this again most likely @JonBons https://github.com/SignalCommunity/Wavelength/commit/fec4c6d4b542d0e305e59a66341dbafc9c4a3a5f

**Comment by JonBons** [comment]
Added code for "respawn" marker via https://github.com/SignalCommunity/SCMF/commit/2b230d3ebf2a5863de66a7fff09eb95180b99ab8

**Comment by JonBons** [comment]
Feature is fully implemented but needs testing.
