### ISSUE TITLE
Move JIPAT Feature to POTATO

### ISSUE THREAD

**Issue by derbismarck** [SignalCommunity/SCMF#19]
Reference issue #5, reference commit [50a7a3f](https://github.com/SignalCommunity/SCMF/commit/50a7a3fe46e3556e289e0141a1ce590ea8fd8e55)

**Comment by JonBons** [comment]
Started work on this here https://github.com/SignalCommunity/POTATO/commit/7ecc7dafc68f8aa3d1f5ca801e2a00dbd4bc4a73

**Comment by JonBons** [comment]
Created pull request https://github.com/SignalCommunity/POTATO/pull/6 but needs testing.
