### ISSUE TITLE
#44 ACRE defaults not working as intended 

### ISSUE THREAD

**Issue by Winifridal** [SignalCommunity/SCMF#44]
Preset ACRE channel settings aren't working when mission is initialized.

**Comment by MysticalPony** [comment]
So this worked fine for the second mission on Wednesday, do we know why?

**Comment by JonBons** [comment]
@Winifridal Is this confirmed to be your derp of disabling the ACRE module?

**Comment by JonBons** [comment]
[10:30 AM] Winifridal: yes confirmed.
[10:30 AM] Winifridal: i has the master enable off rather than on
